### PR TITLE
init_project

### PR DESCRIPTION
**Pull request by nguyenhuuhai98**
Init_project

### CODE REVIEW

**Comment by nguyenhuuhai98** [comment]
ready

**Comment by nguyenhuuhai98** [comment]
ready

**Comment by nguyenhuuhai98** [comment]
ready

**Review by tuannt-0910 — APPROVED** [review]

**Review by huyenttm-0901 — APPROVED** [review]

**Comment by nguyenhuuhai98** [comment]
ready

**Pull request merged**
